### ISSUE TITLE
fix has_link

### ISSUE THREAD

**Issue by agarwal** [solvuu/phat#13]
Since we added `Broken_link`, the meaning of `has_link` is unclear. Do we want it to mean *has non-broken link*? If so, the current definition is still okay. However, maybe `Broken_link` should count as a link too?

Note this failed to arise earlier because of the use of wildcard patterns in `has_link`. We should be avoiding these as much as possible. (Though the one use-case in which I consider wildcard patterns valid is exactly this one, where the function inherently is about a single case. Problem here is that single case got turned into two, so they are always bad!)

**Comment by pveber** [comment]
Summary of our discussion : we keep the definition of `has_link` as it is, because the main motivation for this function is to assert that a path will not change as a result of link resolution.

**Comment by agarwal** [comment]
0fcfecdccbdff55350084e580c0dc9f94d81d74b adds documentation to explain the decision made in this issue, so now closing.
