### ISSUE TITLE
`normalize` should normalize link targets

### ISSUE THREAD

**Issue by agarwal** [solvuu/phat#14]
I can't remember if this was previously discussed, but our current `normalize` doesn't normalize link targets. I feel like it should. The benefits would be:

* The implementation of `equal` would be simplified. We could simply call `Pervasives.equal` after normalizing the two paths. Thus, we could delete `equal_normalized` and `equal_item`, which right now do nothing more than `Pervasives.equal` except for recursively normalizing link targets.

* We could do the same to implement `compare`, which we currently lack and thus cannot easily apply `Comparable.Make`.

On a related note, we should avoid the wildcard pattern in `equal_normalized`. It would be only 1 more line of code to be explicit.

Once this is done, we should `include Comparable.Make`.

**Comment by pveber** [comment]
I implemented `compare`, but I think using `Comparable.Make` is not possible due to type parameter in `Path.t`. Only possibility would be to provide the four variants, should I do it?

**Comment by agarwal** [comment]
Four variants isn't ideal. Let's hold on this.

**Comment by agarwal** [comment]
Let's decide to not call Comparable.Make. Users can call themselves for now in the cases they need it. So closing this issue.
