### ISSUE TITLE
fix Filesys coding style

### ISSUE THREAD

**Issue by agarwal** [solvuu/phat#6]
Few issues to consider:

- [x] In dc22fa65d5f9ddb7943e9af7f75ea5141414592f, a mechanical port of blocking code was done. Probably we need go through all the code and make sure we're using Async's operators appropriately. Done by: e87a434e7ae1341a52cf9e84089a874482d866e2, 54b277eabe9348836a440b6cad2b0f38430a4067, 5a5a1f21c910816078591089c0ed4f7f669abc84.

- [x] Let's standardize on error messaging style. For example, we currently tag error values with the function name, but this is difficult to maintain so let's consider if it is worth it.

**Comment by agarwal** [comment]
Regarding error messages, perhaps we should start using [ppx_here](https://github.com/janestreet/ppx_here/issues). It seems easy to use:
```
utop # #require "ppx_here";;
utop # _here_;;
- : Lexing.position =
{Lexing.pos_fname = "/toplevel"; pos_lnum = 1; pos_bol = 0; pos_cnum = 0}
```

**Comment by pveber** [comment]
14d3fa9 addresses some modifications we discussed.

**Comment by agarwal** [comment]
Looks good. I'm closing this issue.
