### ISSUE TITLE
Filesys.exists: improve return type

### ISSUE THREAD

**Issue by agarwal** [solvuu/phat#7]
`Filesys.exists` currently returns `` `No`` if the path exists but as a different type of object, e.g:

```ocaml
utop # Path.dir_path "/usr" |> ok_exn |> Filesys.exists;;
- : [ `No | `Unknown | `Yes ] = `Yes

utop # Path.file_path "/usr" |> ok_exn |> Filesys.exists;;
- : [ `No | `Unknown | `Yes ] = `No
```

The latter is misleading. One is likely to think the path doesn't exist at all. We should probably include an additional return type: `` `Yes_as_other_object`` to mean the path does exist but not as the type of object you were checking for.

**Comment by agarwal** [comment]
Or perhaps we should define `exists` and `exists_any`. The first one cares about the object type, and the second doesn't.

**Comment by agarwal** [comment]
The function now definitely requires documentation. Once added, I can close this issue.

**Comment by pveber** [comment]
Done!
