### ISSUE TITLE
provide sexp deserializers

### ISSUE THREAD

**Issue by agarwal** [solvuu/phat#8]
ppx_sexp_conv doesn't derive deserializers for GADTs, so we have to do it manually.

**Comment by agarwal** [comment]
Done in 9f93f82443cfa5de962b0b05af454574528d558a, but leaving this open till we add tests.

**Comment by pveber** [comment]
f7b3d88 brings the rephrasing we discussed during the meeting.

**Comment by agarwal** [comment]
Looks like we've handled this issue, so closing.
